# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  serviceName: keycloak-discovery
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:18.0.0
        args: ["start","--auto-build"]
        envFrom:
        - secretRef:
            name: keycloak
            optional: true
        env:
        - name: KC_PROXY
          value: "edge"
        # - name: KC_DB
        #   value: "database_vendor"
        # - name: KC_DB_PASSWORD
        #   value: "database_password"
        # - name: KC_DB_USERNAME
        #   value: "database_username"
        # - name: KC_DB_URL_DATABASE
        #   value: "database_name"
        # - name: KC_DB_URL_HOST
        #   value: "database_host"
        # - name: KC_DB_URL_PORT
        #   value: "database_port"
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_CACHE
          value: "ispn"
        - name: KC_CACHE_STACK
          value: "kubernetes"
        - name: jgroups.dns.query
          value: keycloak-discovery
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - --head
            - --fail
            - --silent
            - http://127.0.0.1:8080/health/ready
          failureThreshold: 250
          initialDelaySeconds: 20
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - curl
            - --head
            - --fail
            - --silent
            - http://127.0.0.1:8080/health/live
          failureThreshold: 150
          initialDelaySeconds: 20
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
