apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - ../../katalog/keycloak
  - namespace.yml

secretGenerator:
  - name: keycloak
    envs:
      - keycloak.env

patchesStrategicMerge:
  - replicas.yml