# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  template:
    spec:
      containers:
        - name: keycloak-operator
          env:
            - name: OPERATOR_KEYCLOAK_IMAGE
              value: registry.sighup.io/fury/keycloak/keycloak-spi-metrics:21.1.1